#!/usr/bin/env python3

import sys
import os
from subprocess import run, PIPE

# Conjure-up specific
sys.path.insert(0, '/usr/share/conjure-up/hooklib')
import juju  # noqa
from writer import log, success, fail, error  # noqa


def main():
    provider_type = os.environ.get('JUJU_PROVIDERTYPE', None)

    if provider_type == "lxd":
        log.debug("Running pre-deploy for OpenStack")

    profilename = run('juju switch | cut -d: -f2', shell=True, stdout=PIPE)

    log.debug("Processing lxd profile: {}".format(
        profilename.stdout.decode().strip()))
    profile_edit = run(
        'sed "s/##MODEL##/{}/" '
        '$SCRIPTPATH/lxd-profile.yaml | '
        'lxc profile edit "juju-$profilename"'.format(profilename),
        shell=True,
        stdout=PIPE,
        stderr=PIPE)

    log.debug(profile_edit.stderr)
    log.debug(profile_edit.stdout)
    log.debug(profile_edit)

    if profile_edit.returncode > 0:
        error(profile_edit.stderr)

    success("Updated LXD profile.")

if __name__ == "__main__":
    main()
